// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// quadratic_1D_mu
List quadratic_1D_mu(NumericVector mu, NumericVector lambda, NumericVector weights);
RcppExport SEXP _RISEX_quadratic_1D_mu(SEXP muSEXP, SEXP lambdaSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(quadratic_1D_mu(mu, lambda, weights));
    return rcpp_result_gen;
END_RCPP
}
// quadratic_1D_coef
List quadratic_1D_coef(NumericMatrix coef, NumericVector lambda);
RcppExport SEXP _RISEX_quadratic_1D_coef(SEXP coefSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(quadratic_1D_coef(coef, lambda));
    return rcpp_result_gen;
END_RCPP
}
// quadratic_cpp
List quadratic_cpp(SEXP A, NumericVector b, NumericVector x0, NumericVector lambda, int max_it, double tol, bool trace);
RcppExport SEXP _RISEX_quadratic_cpp(SEXP ASEXP, SEXP bSEXP, SEXP x0SEXP, SEXP lambdaSEXP, SEXP max_itSEXP, SEXP tolSEXP, SEXP traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type trace(traceSEXP);
    rcpp_result_gen = Rcpp::wrap(quadratic_cpp(A, b, x0, lambda, max_it, tol, trace));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RISEX_quadratic_1D_mu", (DL_FUNC) &_RISEX_quadratic_1D_mu, 3},
    {"_RISEX_quadratic_1D_coef", (DL_FUNC) &_RISEX_quadratic_1D_coef, 2},
    {"_RISEX_quadratic_cpp", (DL_FUNC) &_RISEX_quadratic_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_RISEX(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
