# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quadratic_1D_mu <- function(mu, lambda = as.numeric( c()), weights = 1L) {
    .Call('_RISEX_quadratic_1D_mu', PACKAGE = 'RISEX', mu, lambda, weights)
}

quadratic_1D_coef <- function(coef, lambda = as.numeric( c())) {
    .Call('_RISEX_quadratic_1D_coef', PACKAGE = 'RISEX', coef, lambda)
}

quadratic_cpp <- function(A, b = as.numeric( c()), x0 = as.numeric( c()), lambda = as.numeric( c()), max_it = 1000L, tol = 1e-3, trace = FALSE) {
    .Call('_RISEX_quadratic_cpp', PACKAGE = 'RISEX', A, b, x0, lambda, max_it, tol, trace)
}

